version: "3"
services:
  web:
    build: .
    command: yarn watch-ts
    volumes:
      - .:/usr/src/app/
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:9.6.8-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
